name: Deploy backend to server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy via SSH (password auth)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 91.98.138.1
          username: root
          password: Hdr9RJskEjRd
          command_timeout: 30m
          script: |
            set -e
            cd /opt/anchat/app
            git pull --rebase
            npm run build --workspace server --silent || npm run build --workspace server
            # Ensure PM2 is installed
            if ! command -v pm2 >/dev/null 2>&1; then npm i -g pm2; fi
            # Restart or start API
            pm2 restart anchat-api --silent || pm2 start "node dist/src/main.js" --name anchat-api --cwd /opt/anchat/app/apps/server
            pm2 save --silent || pm2 save
            # Quick health check
            curl -sS http://127.0.0.1:4000/tt/rtm-status || true

